name: DEPLOY_
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /home10/afterrandom/public_html
        remote_host: afterrandom.com.ar
        remote_user: afterrandom
        remote_port: 9022
        remote_key: ${{ secrets.SSH_PRIV_KEY }}