name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: rsync deployments
    #   uses: burnett01/rsync-deployments@5.1
    #   with:
    #     switches: -avzr --delete
    #     path: /
    #     remote_path: /home10/afterrandom/public_html
    #     remote_host: afterrandom.com.ar
    #     remote_user: afterrandom
    #     remote_port: 9022
    #     remote_key: ${{ secrets.SSH_PRIV_KEY }}
    - name: Sync
      env:
        dest: 'afterrandom@afterrandom.com.ar:/home10/afterrandom/public_html'
      run: |
        echo "${{secrets.SSH_PRIV_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -avzh --delete \
          -e 'ssh -p 9022 -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          ./ ${{env.dest}}